type User {
    id: ID!
    name: String!
    login: String!
    email: String!
    role: String!
    createdAt: String!
}

type Project {
    id: ID!
    createdAt: String!
    updatedAt: String!
    name: String!
    description: String!
    logoUrl: String!
    progress: Int!

    lead: Member!
    members: [Member!]!
    boards: [Board!]!
}

type Message {
    id: ID!
    content: String!
    createdAt: String!
    updatedAt: String!
    cardId: String!
    sender: Member!
    replyTo: Message
    replies: [Message!]!
}

type Member {
    id: ID!
    role: String!
    directions: [String!]!
    createdAt: String!
    projectId: String!
    user: User!
}

type Card {
    id: ID!
    title: String!
    content: String!
    priority: String!  
    createdAt: String!
    updatedAt: String!
    boardId: String!

    assignees: [Member!]!
    messages: [Message!]!
}

type Board {
    id: ID!
    name: String!
    direction: String!
    createdAt: String!
    updatedAt: String!
    projectId: String!

    cards: [Card!]!
}

type Schema {
    id: ID!
    direction: String
    url: String!
    name: String!
    author: Member!
    createdAt: String!
    updatedAt: String!
}

type Query {
    
    project(id: ID!): Project!
    
    projects(userId: ID!): [Project!]!
    
    message(id: ID!): Message!

    messages(cardId: ID!): [Message!]!

    board(id: ID!): Board!

    boards(projectId: ID!): [Board!]!
    
    card(id: ID!): Card!

    cards(boardId: ID!): [Card!]!
    
    member(id: ID!): Member!

    members(projectId: ID!): [Member!]!

}