// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Direction string  `json:"direction"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	ProjectID string  `json:"projectId"`
	Cards     []*Card `json:"cards"`
}

type Card struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	Priority  string     `json:"priority"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	BoardID   string     `json:"boardId"`
	Assignees []*Member  `json:"assignees"`
	Messages  []*Message `json:"messages"`
}

type Member struct {
	ID         string   `json:"id"`
	Role       string   `json:"role"`
	Directions []string `json:"directions"`
	CreatedAt  string   `json:"createdAt"`
	ProjectID  string   `json:"projectId"`
	User       *User    `json:"user"`
}

type Message struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	CardID    string     `json:"cardId"`
	Sender    *Member    `json:"sender"`
	ReplyTo   *Message   `json:"replyTo,omitempty"`
	Replies   []*Message `json:"replies"`
}

type Project struct {
	ID          string    `json:"id"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	LogoURL     string    `json:"logoUrl"`
	Progress    int32     `json:"progress"`
	Lead        *Member   `json:"lead"`
	Members     []*Member `json:"members"`
	Boards      []*Board  `json:"boards"`
}

type Query struct {
}

type Schema struct {
	ID        string  `json:"id"`
	Direction *string `json:"direction,omitempty"`
	URL       string  `json:"url"`
	Name      string  `json:"name"`
	Author    *Member `json:"author"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Login     string `json:"login"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}
